CREATE TABLE IF NOT EXISTS gastos_variaveis_itens (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  empresa_id INTEGER NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  valor REAL NOT NULL DEFAULT 0
);
