CREATE TABLE IF NOT EXISTS lancamentos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  empresa_id INTEGER NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
  data TEXT NOT NULL,
  vendas REAL NOT NULL DEFAULT 0,
  itens TEXT NOT NULL DEFAULT '[]',
  obs TEXT NOT NULL DEFAULT '',
  criado_em TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS socios (
  empresa_id INTEGER NOT NULL PRIMARY KEY REFERENCES empresas(id) ON DELETE CASCADE,
  dados TEXT NOT NULL DEFAULT '[]'
);
